name: TubeSync
slug: tubesync
version: "0.1.0"
description: Sync your media library with YouTube
image: ghcr.io/meeb/tubesync
arch: [aarch64, amd64]
ingress: true
ingress_port: 4848
startup: services
boot: auto
map:
  - media:rw        # Emby reads this
  - addon_config:rw # TubeSync stores config/db here
environment:
  TZ: America/New_York
  PUID: "0"
  PGID: "0"
