---
name: AppDaemon
version: 0.17.4
slug: appdaemon
description: Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
url: https://github.com/hassio-addons/addon-appdaemon
startup: application
services:
- mqtt:need
arch:
- aarch64
- amd64
boot: auto
init: false
uart: true
homeassistant_api: true
hassio_api: true
panel_icon: mdi:zigbee
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: AppDaemon
options:
  system_packages: []
  python_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
  - str
  python_packages:
  - str
  init_commands:
  - str
image: ghcr.io/hassio-addons/appdaemon/{arch}
