name: "Tandoor"
description: "The recipe manager that allows you to manage your ever growing collection of digital recipes."
version: "1.5.24"
slug: "tandoor"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080