name: "Tandoor"
description: "The recipe manager that allows you to manage your ever growing collection of digital recipes"
version: "1.5.24.9"
slug: "tandoor"
panel_icon: mdi:silverware-fork-knife
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
ingress: true